version: 0.0.{build}.{branch}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  project: CrosswordCreator.sln
  verbosity: minimal
test_script:
- cmd: dotnet test tests/CrosswordCreatorTests.fsproj
